### ISSUE TITLE
Browsers off spec? SVG maps to "group" but the spec suggests it should map to "graphics-document"

### ISSUE THREAD

**Issue by brennanyoung** [w3c/svg-aam#22]
I ended up on a bit of a wild goose chase because the SVG-AAM spec indicates that SVG should map to `graphics-document` by default, although it is unclear whether this is SVG in the context of SVG, or whether it also applies to SVG in the context of HTML. I simply can't figure it out.

https://www.w3.org/TR/svg-aam-1.0/#mapping_role mentions a default mapping for SVG
https://github.com/w3c/html-aam/issues/43 contains the discussion which led to the change.

Questions:
Where does an author look to find unambiguous specifications about SVG default role mappings? Is it actually specified? Where?

If a SVG conveys meaning (e.g. a histogram) and an author omits an explicit role, will other aria (such as `aria-roledescription` or `aria-label`) still work?

Is this important enough to worry about? 
If it is, I suggest that either we revert the change in the spec, or lobby the browser vendors to implement the change.

In general, I find the role mapping for SVG and graphics-aria horribly complicated and difficult to understand. Is there any chance we could clarify this?

**Comment by cookiecrook** [comment]
@brennanyoung I think this behavior is just an artifact of: 

1. Graphics-ARIA and SVG-AAM came into existence relatively recently. 
2. These specs have never be fully testable.
3. The accessibility internals predate this spec by a decade or more. (Probably including the `group` mapping)
4. No one has complained, because the difference has very little direct user impact.

I'm trying to change item 2 with https://github.com/web-platform-tests/interop-accessibility/issues/69 but I think https://github.com/w3c/svg-aam/issues/18 will be the more impactful issue related to your question above. 

I think this issue can be closed in favor of one or both of the other too, but please clarify if you think it needs to stay open. Otherwise close it, or I can next time I come across it.

**Comment by cookiecrook** [comment]
Also the behavior of parent role versus extension spec subclass role was never really defined until this year:
- https://github.com/w3c/aria/issues/1887

**Comment by brennanyoung** [comment]
let this be handled under #18
